"""README.txt generator for digital delivery files."""
from __future__ import annotations

from datetime import datetime
from typing import Dict, Any

from ..config import PackConfig

# Screen type display names
SCREEN_TYPE_NAMES = {
    "starting": "Starting Screen",
    "live": "Live Stream Overlay",
    "brb": "BRB (Be Right Back) Screen",
    "ending": "Ending Screen",
    "thumbnail_background": "Thumbnail Background",
}

# README template with dynamic fields
README_TEMPLATE = """=================================================================
  {pack_name} - {screen_type}
=================================================================

Thank you for your purchase!

WHAT'S INCLUDED:
- {variant_count} high-quality PNG overlay images ({resolution})
- Ready to use in OBS Studio, Streamlabs, or any streaming software
- Professional design with brand consistency

HOW TO USE:
1. Extract this ZIP file to a folder on your computer
2. Open your streaming software (OBS Studio, Streamlabs, etc.)
3. Add Image Source → Browse → Select your preferred variant
4. Resize/position as needed
5. Add text overlays for titles, alerts, channel name, etc.

TECHNICAL SPECS:
- Format: PNG with transparency (where applicable)
- Resolution: {width}x{height} pixels
- Color Profile: sRGB
- Optimized for: 1080p/1440p streaming
- File size: ~2-5MB per image

CUSTOMIZATION TIPS:
- Add your channel name/logo using text layers in OBS
- Adjust opacity (50-90%) for different moods
- Combine with animated alerts for extra flair
- Use color filters in OBS to match your brand
- Layer multiple variants for unique effects

THEME: {theme}
STYLE: {mood_keywords}
COLOR PALETTE: {color_palette}

LICENSE:
✓ Personal and commercial use allowed for streaming content
✓ Use in YouTube, Twitch, Facebook Gaming, etc.
✓ Modify and customize for your channel
✗ You may NOT resell or redistribute these files
✗ You may NOT claim as your own creation

SUPPORT:
Questions or issues? Contact us on Etsy!
We're here to help you create amazing streams.

CREDITS:
Generated by Stream Pack Builder
AI-powered design with multi-agent quality assurance
Generated on: {generation_date}

=================================================================
Enjoy your new stream overlays! 🎮✨
=================================================================
"""


def generate_readme(
    pack_name: str,
    screen_type: str,
    config: PackConfig,
    variant_count: int = 3,
) -> str:
    """Generate README.txt content for a screen type.

    Args:
        pack_name: Name of the pack (e.g., "neon_cyberpunk")
        screen_type: Screen type key (e.g., "starting", "brb")
        config: Pack configuration
        variant_count: Number of variants included (default 3)

    Returns:
        README text content with dynamic fields populated
    """
    # Get display name for screen type
    screen_type_display = SCREEN_TYPE_NAMES.get(screen_type, screen_type.replace("_", " ").title())

    # Extract brand info
    mood_keywords = "modern, professional, engaging"
    color_palette = "Custom color scheme"

    if config.brand_tokens:
        mood_keywords = config.brand_tokens.mood or mood_keywords
        primary_colors = config.brand_tokens.primary_colors or []
        if primary_colors:
            color_palette = ", ".join(primary_colors[:3])

    # Build dynamic fields
    fields = {
        "pack_name": pack_name.replace("_", " ").title(),
        "screen_type": screen_type_display,
        "variant_count": variant_count,
        "resolution": f"{config.resolution.width}x{config.resolution.height}",
        "width": config.resolution.width,
        "height": config.resolution.height,
        "theme": config.theme,
        "mood_keywords": mood_keywords,
        "color_palette": color_palette,
        "generation_date": datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
    }

    # Populate template
    readme_content = README_TEMPLATE.format(**fields)

    return readme_content


def generate_master_readme(
    pack_name: str,
    config: PackConfig,
    total_files: int = 12,
) -> str:
    """Generate master README.txt for the entire pack.

    This README provides an overview of all files in the pack.

    Args:
        pack_name: Name of the pack
        config: Pack configuration
        total_files: Total number of PNG files included

    Returns:
        Master README text content
    """
    mood_keywords = "modern, professional"
    if config.brand_tokens:
        mood_keywords = config.brand_tokens.mood or mood_keywords

    master_template = """=================================================================
  {pack_name} - COMPLETE STREAM PACK
=================================================================

Thank you for your purchase!

WHAT'S INCLUDED:
This pack contains {total_files} professional stream overlay images across 4 categories:

📺 STARTING SCREEN (3 variants)
   - Use when your stream is about to begin
   - Build anticipation with viewers

💬 BRB SCREEN (3 variants)
   - Use during short breaks
   - Keep viewers engaged while you're away

🎬 ENDING SCREEN (3 variants)
   - Use to close your stream professionally
   - Thank viewers and promote social media

🖼️ THUMBNAIL BACKGROUNDS (3 variants)
   - Use for YouTube/Twitch thumbnails
   - Consistent branding across platforms

QUICK START:
1. Extract all ZIP files to your computer
2. Open OBS Studio or your streaming software
3. Add Image Source for each screen type
4. Customize with your text, logo, and alerts
5. Start streaming with professional overlays!

THEME: {theme}
STYLE: {mood_keywords}
RESOLUTION: {resolution}

FULL DOCUMENTATION:
Each ZIP file contains its own README.txt with detailed instructions.

LICENSE:
✓ Personal and commercial streaming use
✗ No resale or redistribution

SUPPORT:
Questions? Contact us on Etsy!

Generated: {generation_date}
=================================================================
"""

    fields = {
        "pack_name": pack_name.replace("_", " ").title(),
        "total_files": total_files,
        "theme": config.theme,
        "mood_keywords": mood_keywords,
        "resolution": f"{config.resolution.width}x{config.resolution.height}",
        "generation_date": datetime.now().strftime("%Y-%m-%d"),
    }

    return master_template.format(**fields)


__all__ = [
    "generate_readme",
    "generate_master_readme",
    "SCREEN_TYPE_NAMES",
]
